version: "3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - textstats:app

  textstats:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
