"""
Unicode constants &c
"""

VG_UNICODE_PUNCT = [
    '\u00a0', # NO-BREAK SPACE
    '\u00a3', # POUND SIGN
    '\u00b0', # DEGREE SIGN
    '\u00b1', # PLUS-MINUS SIGN
    '\u00b4', # ACUTE ACCENT
    '\u00b7', # MIDDLE DOT
    '\u00bb', # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    '\u00bd', # VULGAR FRACTION ONE HALF
    '\u2013', # EN DASH
    '\u2014', # EM DASH
    '\u2018', # LEFT SINGLE QUOTATION MARK
    '\u201c', # LEFT DOUBLE QUOTATION MARK
    '\u201d', # RIGHT DOUBLE QUOTATION MARK
    '\u2026', # HORIZONTAL ELLIPSIS
    '\u2500', # BOX DRAWINGS LIGHT HORIZONTAL
    '\u25a1', # WHITE SQUARE
    '\u2019', # RIGHT SINGLE QUOTATION MARK
]
